# Generated by Django 4.1.5 on 2023-01-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Album name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('main_picture', models.ImageField(default='photos/default/album_main.jpg', upload_to='photos/albums/%Y/', verbose_name='Main picture')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update time')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Site name')),
                ('css_class', models.CharField(max_length=255, verbose_name='Link Type')),
            ],
            options={
                'verbose_name': 'Link type',
                'verbose_name_plural': 'Link types',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/works/%Y/%m/%d/', verbose_name='Photo')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Add time')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters_app.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Surname')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('user_photo', models.ImageField(blank=True, default='photos/default/user_photo.jpg', upload_to='photos/users/%Y/', verbose_name='Photo')),
                ('tg_id', models.IntegerField(blank=True, unique=True, verbose_name='Telegram ID')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='masters_app.category', verbose_name='Category')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='masters_app.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters_app.linktype', verbose_name='link type')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters_app.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters_app.page', verbose_name='Page'),
        ),
    ]
